### ISSUE TITLE
Invalid_argument("Lwt.wakeup_result") when closing a connection

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-tcpip#153]
I have a simple TCP test client that writes a single byte and then closes the connection:

    match_lwt S.TCPV4.create_connection t (laptop_ip, 7001) with
    | `Error _err -> failwith "TCP error 7001"
    | `Ok flow ->
    
    let payload = Cstruct.sub buffer 0 1 in
    Cstruct.set_char payload 0 '!';

    match_lwt S.TCPV4.write flow payload with
    | `Error _ | `Eof -> assert false
    | `Ok () ->

    S.TCPV4.close flow >>= fun () ->
    OS.Time.sleep 1.0

Looking at a trace of this, I see some failed threads showing `Invalid_argument("Lwt.wakeup_result")`. It looks like `rx_application_t` tries to do `Lwt.wakeup urx_close_u ()` twice (the `data = None` case happens twice).

Not sure if it's a problem, but I guess that isn't supposed to happen...

![lwt-wakeup-fail](https://cloud.githubusercontent.com/assets/554131/8181312/c420d29a-141c-11e5-832a-f84abdc4fe9e.png)

**Comment by talex5** [comment]
@yomimono / @balrajsingh any thoughts on how to fix this error?

    Fatal error: exception Invalid_argument("Lwt.wakeup_result")

What is the correct behaviour when closing a connection?
The error is coming from here:

https://github.com/mirage/mirage-tcpip/blob/455263dcc47409fbb1266c8a6553230a8b6f6d87/tcp/pcb.ml#L211

It looks like it sets `urx_close_u` and then calls itself recursively, which then tries to do it again.

To reproduce the bug, just apply the patch in #154 (which stops the error being silently ignored) and run the unit tests. You can see the error in the [Travis log](https://travis-ci.org/mirage/mirage-tcpip/jobs/67199445).

**Comment by yomimono** [comment]
@talex5 - I'm looking at this now; I need to do a bit of puzzling over it before I have any suggestions.

**Comment by yomimono** [comment]
It might be a good idea to page @MagnusS as well, as I know he was looking into mvar use in this chunk of code a while back. At first glance I'm not sure why we have `urx_close_u` and `urx_close_t` at all.

**Comment by balrajsingh** [comment]
Doesn't look great, does it.  I too need to look at it more carefully and
think it about again.

The urx_close_u and urx_close_t was probably for an out-of-band close, ie
an RST.  I think for now removing that mechanism is fine since nothing uses
it.  Right now a FIN and RST appear to be the same to the application,
which is ok.

Also the recursive call on the None branch does look wrong - it shouldn't
be there.  But at the same time there shouldn't be multiple end of stream
messages reaching here.  This probably happens when duplicate FINs are
received or if a FIN and an RST is received.  At first thought the fix may
be to just check state before pushing the signal up to the application.  So
if a FIN or RST has been received and sent on to the application, then it
shouldn't send it again.

**Comment by talex5** [comment]
Fixed by #156
