### ISSUE TITLE
A stress test on my SMTP server show me an unknow error

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage-tcpip#456]
When I try to stress-test my SMTP server which mostly retransmit an incoming email to an other point, I got this error message:
```
console data 2021-10-25T17:05:54-00:00: 2021-10-25 17:05:54 -00:00: ERR [netif] [listen] error while handling Lwt_stream.Full, continuing. bt: Raised at Stdlib__hashtbl.find in file "hashtbl.ml", line 541, characters 17-32
```

I'm not sure about what such error refers, someone knows about such error? And in which context it appears? Currently, you can reproduce it with these unikernels: https://github.com/dinosaure/ptt/tree/master/unikernel

Btw, is it possible to test locally without Solo5 the `mirage-tcpip` stack (not the unix/socket one)?

**Comment by hannesm** [comment]
Thanks for the investigations @dinosaure. I've to pass on the current TCP stack / what the segment module is doing. If your patch fixes the memory issue you encounter, I'd be in favour to push and release that.

**Comment by dinosaure** [comment]
I need to investigate more (but I will do next week probably - vacation) because `Netif.listen` stills leak a memory even if you applied this patch.

**Comment by dinosaure** [comment]
I can confirm that the current patch fix the memory leak for `mirage-tcpip` even if it seems that few TCP/IP packets remains for whatever reasons. We probably should integrate the patch indeed @hannesm - but it seems that I found an other memory leak on my SMTP server.

**Comment by dinosaure** [comment]
My last experiment show that we still have a leak on `Netif.*` functions:
<img width="293" alt="capture003" src="https://user-images.githubusercontent.com/321910/143222394-d2a283f8-c86d-4458-9016-ef3a14eff0c4.PNG">

`module` is how many objects which came from `Netif.*` are alive. The server `Out_of_memory` with few packets:
```
>>>> remaining packets (009) <<<<
>>> 824286: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0028 abc6 4000 4006 0bb4 c0a8 0102 c0a8  .(..@.@.........
            00000020: 0103 0019 8c13 5eac 6ba4 8fb2 65e0 5010  ......^.k...e.P.
            00000030: 00a5 dfc9 0000                           .......
>>> 824310: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0028 0000 4000 4006 b77a c0a8 0102 c0a8  .(..@.@..z......
            00000020: 0103 0019 8c13 5eac 6ba4 8fb2 65e0 5010  ......^.k...e.P.
            00000030: 00a5 dfc9 0000                           .......
>>> 824278: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0040 e4da 4000 4006 d287 c0a8 0102 c0a8  .@..@.@.........
            00000020: 0103 0019 8c12 6e06 23f0 fbab d84b 5019  ......n.#....KP.
            00000030: 00a5 8727 0000 1703 0300 1300 d566 3c95  ...'.........f<.
            00000040: 5860 5590 3f4f 48bb 99e5 0286 a111       X`U.?OH........
>>> 824285: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0040 abc5 4000 4006 0b9d c0a8 0102 c0a8  .@..@.@.........
            00000020: 0103 0019 8c13 5eac 6b8b 8fb2 65df 5019  ......^.k...e.P.
            00000030: 00a5 7b23 0000 1703 0300 133e edc8 a666  ..{#.......>...f
            00000040: 11b9 2283 cd54 1d03 567e fe31 2fea       .."..T..V~.1/..
>>> 824274: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0028 6fae 4000 4006 47cc c0a8 0102 c0a8  .(o.@.@.G.......
            00000020: 0103 0019 8c10 3b66 d517 aca5 2920 5010  ......;f....) P.
            00000030: 00a5 b96c 0000                           ...l...
>>> 824304: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0028 0000 4000 4006 b77a c0a8 0102 c0a8  .(..@.@..z......
            00000020: 0103 0019 8c10 3b66 d517 aca5 2920 5010  ......;f....) P.
            00000030: 00a5 b96c 0000                           ...l...
>>> 824279: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0028 e4db 4000 4006 d29e c0a8 0102 c0a8  .(..@.@.........
            00000020: 0103 0019 8c12 6e06 2409 fbab d84c 5010  ......n.$....LP.
            00000030: 00a5 39a6 0000                           ..9....
>>> 824273: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0040 6fad 4000 4006 47b5 c0a8 0102 c0a8  .@o.@.@.G.......
            00000020: 0103 0019 8c10 3b66 d4fe aca5 291f 5019  ......;f....).P.
            00000030: 00a5 ae51 0000 1703 0300 13dd 3d77 32c7  ...Q........=w2.
            00000040: e48b fe75 3bef aa5f 73bf eed1 4113       ...u;.._s...A..
>>> 824307: 00000000: a201 9ed0 ccd7 8e35 4374 8166 0800 4500  .......5Ct.f..E.
            00000010: 0028 0000 4000 4006 b77a c0a8 0102 c0a8  .(..@.@..z......
            00000020: 0103 0019 8c12 6e06 2409 fbab d84c 5010  ......n.$....LP.
            00000030: 00a5 39a6 0000                           ..9....
```

Some is about ACK, some about [FIN, PSH, ACK] [TCP segment of a reassembled PDU] and all of them come from `mirage-tcpip` (the server) to transmit something to the client. Note that even if this packet seems small, `Netif` allocates a buffer of `MTU` bytes (in my case, 1500 bytes. 9 remaining packets is 13,5 Kbytes. It's a shame to not have a _vertical scale_ on these outputs but it seems clear that even if I applied my previous patch, we still have a memory leak.

On the application level, I can assert that every `Lwt.async` used finish correctly and memory are released. At this stage, I don't really know what I need to do.

**Comment by balrajsingh** [comment]
Wow!  This is an extremely well done investigation.  Much appreciation to you @dinosaure for your tenaciousness. 

It's been a long time since I saw this code so please pardon my slowness.  My first thought was that the RST path had been very under-tested so it's not surprising that there are problems.

There may be more than one leak here but the one you identified when multiple valid RST segments are received, is definitely a problem.  The suggested fix of checking if the rx_data mvar is empty before putting it will probably not always work.  It will only work if the RST segments are timed so that the second and later ones are prevented from causing the mvar put because the first has not yet been taken.  If the RST segment arrivals are timed so the mvar put from the first RST gets processed, which means that the thread that takes the mvar terminates, and then after that if a valid RST arrives causing a put, the mvar would never get read and it would be a leak.

I think the fix should involve the state machine where once one valid RST segment is accepted no further RSTs should be accepted.  Would it be possible for you to test the following changes.  There are two changes below, could you try them separately too?  Unfortunately I don't have a functioning environment for mirage right now.

```
diff --git a/src/tcp/segment.ml b/src/tcp/segment.ml
index 0394c5fa..d685ed3e 100644
--- a/src/tcp/segment.ml
+++ b/src/tcp/segment.ml
@@ -110,12 +110,17 @@ module Rx(Time:Mirage_time.S) = struct

   let check_valid_segment q seg =
     if seg.header.rst then
-      if Sequence.compare seg.header.sequence (Window.rx_nxt q.wnd) = 0 then
-        `Reset
-      else if Window.valid q.wnd seg.header.sequence then
-        `ChallengeAck
-      else
-        `Drop
+      begin match State.state q.state with
+        | State.Reset ->
+          `Drop
+        | _ ->
+          if Sequence.compare seg.header.sequence (Window.rx_nxt q.wnd) = 0 then
+            `Reset
+          else if Window.valid q.wnd seg.header.sequence then
+            `ChallengeAck
+          else
+            `Drop
+      end
     else if seg.header.syn then
       `ChallengeAck
     else if Window.valid q.wnd seg.header.sequence then
@@ -131,7 +136,9 @@ module Rx(Time:Mirage_time.S) = struct
   let send_challenge_ack q =
     (* TODO:  rfc5961 ACK Throttling *)
     (* Is this the correct way trigger an ack? *)
-    Lwt_mvar.put q.rx_data (Some [], Some Sequence.zero)
+    if Lwt_mvar.is_empty q.rx_data
+      then Lwt_mvar.put q.rx_data (Some [], Some Sequence.zero)
+      else Lwt.return_unit

   (* Given an input segment, the window information, and a receive
      queue, update the window, extract any ready segments into the
```

**Comment by dinosaure** [comment]
Hi @balrajsingh,

Firstly, thank you for your time to help us to investigate this memory leak. It's not easy to go deeper in this codebase. From what you explain, I think you highlight the reason about why, even with my initial patch, I still continue to have the memory leak. 

Then, I relaunched my huge test (which is: send ONE MILLION emails to the server) with your patch and it's seems that we don't have any memory leaks 🎉 ! I get an other problem (which is more about the time spent to try a connection which is long and put a pressure on the GC which is not allowed to release resource until we fail) but it's no more about `mirage-crypto`/`mirage-tcpip` 👍 .

So really thank you to help us about that because it unlock us about sustainability of many of our services (such as the SMTP service). Hope that this patch will solve the issue discovered by @hannesm before too. I will definitely propose a PR to integrate your patch (with you as an author) and cut a release. WDYT?

And again, big thanks!

**Comment by balrajsingh** [comment]
Hooray!  That is most excellent @dinosaure.  It's really great to hear that it worked.  Yes please do propose a PR, I feel quite comfortable with fixing the multiple valid RST problem in this way.

About memory use when lots of connections are being tried, and re-tried when some fail due to packet loss, that is just the way that this design works.  It does try to delay creating all the required threads and data structures till a connection is almost ready to be in the Established state, but still the minimum that it allocates for each connection as it attempts to reach the Established state will add up.  We may need some clever design improvement to somehow not use any memory at all till the connection is fully ready to be Established.  At the same time, it could just be considered one of the capacity limits for this stack - as long as the limit is high enough it is probably ok.

**Comment by dinosaure** [comment]
Thanks everybody for this fix :+1:!
